# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode9.2

branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
script:
  - xcodebuild -workspace Example/EFInternetIndicator.xcworkspace -scheme EFInternetIndicator-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
