# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8.0
# blacklist
branches:
  except:
    - auth
script:
- set -o pipefail
- xcodebuild -workspace Example/EFInternetIndicator.xcworkspace -scheme EFInternetIndicator-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --quick --allow-warnings
